# Generated by Django 4.0.5 on 2022-06-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
